FROM almalinux:9
ENV course="DevSecOps With Cloud" \
    trainer="Shiva Kumar Reddy" \
    duration="120Hrs"
ARG ${username:-some_user}
RUN echo "Hello ${username}" > /tmp/devops.txt
CMD ["sleep", "100"]